#ifndef SYSTICK_PRIVATE_H
#define SYSTICK_PRIVATE_H

#define SET_BIT(REG_NAME, BIT_NUMBER) REG_NAME |= (1 << BIT_NUMBER)
#define CLEAR_BIT(REG_NAME, BIT_NUMBER) REG_NAME &= (~(1 << BIT_NUMBER))

#endif